name: Backend Continuous Deployment

on:
  # Automatic trigger on push events to the main branch
  push:
    branches:
      - master
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - master
    paths:
      - 'starter/frontend/**'
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

jobs:
  # Pythonコードのリントを行うジョブ
  lint:
    runs-on: ubuntu-latest # ジョブは最新のUbuntuで実行されます
    steps:
      # コードをGitHubリポジトリからチェックアウトするステップ
      - name: Checkout code
        uses: actions/checkout@v2

      # Python 3.9のセットアップを行うステップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Pythonのバージョンを指定

      # 必要なPython依存関係をインストールするステップ
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
        working-directory: starter/backend # starter/backendディレクトリでコマンドを実行

      # Lintを実行するステップ
      - name: Run Lint
        run: |
          pipenv run lint
        working-directory: starter/backend # starter/backendディレクトリでコマンドを実行
          
  # Pythonコードのテストを実行するジョブ
  test:
    runs-on: ubuntu-latest # ジョブは最新のUbuntuで実行されます
    steps:
      # コードをGitHubリポジトリからチェックアウトするステップ
      - name: Checkout code
        uses: actions/checkout@v2

      # Python 3.9のセットアップを行うステップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Pythonのバージョンを指定

      # 必要なPython依存関係をインストールするステップ
      - name: Install dependencies
        run: |
          cd starter/backend
          pip install pipenv
          pipenv install --dev

      # テストを実行するステップ
      - name: Run Tests
        run: pipenv run test # テストコマンドを実行
        working-directory: starter/backend # starter/backendディレクトリでコマンドを実行
  
  # Dockerイメージをビルドし、ECRにプッシュするジョブ
  build:
    runs-on: ubuntu-latest # ジョブは最新のUbuntuで実行されます
    needs: [lint, test] # lintおよびtestジョブが成功した場合のみ実行
    steps:
      # コードをGitHubリポジトリからチェックアウトするステップ
      - name: Checkout code
        uses: actions/checkout@v2

      # Dockerイメージをビルドするステップ
      - name: Build Docker image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .

      # AWSの資格情報を設定するステップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCOUNT_ID }} # AWSアクセスキーIDを設定
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWSシークレットアクセスキーを設定
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          # aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1

      # Amazon ECRへのログインを行うステップ
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Dockerイメージにタグを付けるステップ
      - name: Tag Docker image
        run: |
          docker tag mp-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME_BACKEND }}:${{ github.sha }}

      # DockerイメージをECRにプッシュするステップ
      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME_BACKEND }}:${{ github.sha }} # タグを付けたDockerイメージをECRにプッシュ
          
  # EKSにデプロイするジョブ
  deploy:
    runs-on: ubuntu-latest # ジョブは最新のUbuntuで実行されます
    needs: build # buildジョブが成功した場合のみ実行
    steps:
      # コードをGitHubリポジトリからチェックアウトするステップ
      - name: Checkout code
        uses: actions/checkout@v2

      # AWSの資格情報を設定するステップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCOUNT_ID }} # AWSアクセスキーIDを設定
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWSシークレットアクセスキーを設定
          aws-region: ${{ vars.AWS_REGION }} # AWSリージョンを設定

      # kubeconfigを更新してEKSクラスターにアクセスできるようにするステップ
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }} # EKSクラスターのkubeconfigを更新

      # Kubernetesのマニフェストで新しいイメージタグを設定するステップ
      - name: Set new image tag in Kubernetes manifests
        run: kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME_BACKEND }}:${{ github.sha }} # kustomizeで新しいDockerイメージタグを設定
        working-directory: starter/backend/k8s # k8sディレクトリでコマンドを実行

      # Kubernetesマニフェストを適用するステップ
      - name: Apply Kubernetes manifests
        run: kustomize build | kubectl apply -f - # kustomizeでビルドしたKubernetesマニフェストを適用
        working-directory: starter/backend/k8s # k8sディレクトリでコマンドを実行
